Update workflow-artifacts-errors-retry.yml

diff --git a/.github/workflows/workflow-artifacts-errors-retry.yml b/.github/workflows/workflow-artifacts-errors-retry.yml
--- a/.github/workflows/workflow-artifacts-errors-retry.yml
+++ b/.github/workflows/workflow-artifacts-errors-retry.yml
@@ -12,15 +12,28 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - run: dd if=/dev/zero of=bigfile.zip bs=1M count=600
-      - uses: actions/upload-artifact@v3.1.3 
+      - uses: actions/upload-artifact@v3
         with:
           name: large
           path: bigfile.zip
+      - name: Download artifact
+        uses: actions/download-artifact@v3
+        with:
+          name: large
 
   secrets-error:
     runs-on: ubuntu-latest
     steps:
       - run: git clone https://github.com/HemalaDev57/gha-repo-1.git
+  
+  install-deps-fail:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Success step
+        run: sleep 5
+      - name: Install dependencies
+        run: exit 1  # Consistent failure at specific step
+
 
   redundant-steps:
     runs-on: ubuntu-latest
@@ -30,12 +43,59 @@ jobs:
       - run: echo "step 1"  # Repeated
       - run: echo "step 2"  # Repeated
       - run: echo "step 3"
+      - run: echo "step 1"
+      - run: echo "step 2"
+      - run: echo "step 1"  # Repeated
+      - run: echo "step 2"  # Repeated
+      - run: echo "step 3"
+      - run: echo "step 1"
+      - run: echo "step 2"
+      - run: echo "step 1"  # Repeated
+      - run: echo "step 2"  # Repeated
+      - run: echo "step 3"
+      - run: echo "step 1"
+      - run: echo "step 2"
+      - run: echo "step 1"  # Repeated
+      - run: echo "step 2"  # Repeated
+      - run: echo "step 3"
+      - run: echo "step 1"
+      - run: echo "step 2"
+      - run: echo "step 1"  # Repeated
+      - run: echo "step 2"  # Repeated
+      - run: echo "step 3"
+      - run: echo "step 1"
+      - run: echo "step 2"
+      - run: echo "step 1"  # Repeated
+      - run: echo "step 2"  # Repeated
+      - run: echo "step 3"
+      - run: echo "step 1"
+      - run: echo "step 2"
+      - run: echo "step 1"  # Repeated
+      - run: echo "step 2"  # Repeated
+      - run: echo "step 3"
+      - run: echo "step 1"
+      - run: echo "step 2"
+      - run: echo "step 1"  # Repeated
+      - run: echo "step 2"  # Repeated
+      - run: echo "step 3"
+      - run: echo "step 1"
+      - run: echo "step 2"
+      - run: echo "step 1"  # Repeated
+      - run: echo "step 2"  # Repeated
+      - run: echo "step 3"
+      - run: echo "step 1"
+      - run: echo "step 2"
+      - run: echo "step 1"  # Repeated
+      - run: echo "step 2"  # Repeated
+      - run: echo "step 3"
+      - run: echo "step 1"
+      - run: echo "step 2"
+      - run: echo "step 1"  # Repeated
+      - run: echo "step 2"  # Repeated
+      - run: echo "step 7"
+      - run: echo "step 6"
+      - run: echo "step 5"
+      - run: echo "step 1"  # Repeated
+      - run: echo "step 2"  # Repeated
+      - run: echo "step 4"
       # Add up to 30+ steps to simulate too many steps
-
-  install-deps-fail:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Success step
-        run: sleep 5
-      - name: Install dependencies
-        run: exit 1  # Consistent failure at specific step
